//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.10 at 11:23:54 AM COT 
//


package org.example.cliente;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.cliente package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClienteType_QNAME = new QName("http://www.example.org/cliente", "clienteType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.cliente
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClienteType }
     * 
     */
    public ClienteType createClienteType() {
        return new ClienteType();
    }

    /**
     * Create an instance of {@link ClienteEntidadResponse }
     * 
     */
    public ClienteEntidadResponse createClienteEntidadResponse() {
        return new ClienteEntidadResponse();
    }

    /**
     * Create an instance of {@link ClienteRequest }
     * 
     */
    public ClienteRequest createClienteRequest() {
        return new ClienteRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClienteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/cliente", name = "clienteType")
    public JAXBElement<ClienteType> createClienteType(ClienteType value) {
        return new JAXBElement<ClienteType>(_ClienteType_QNAME, ClienteType.class, null, value);
    }

}
