//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.10 at 11:23:36 AM COT 
//


package org.example.cliente;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.cliente package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CuentaSaldo_QNAME = new QName("http://www.example.org/Cliente", "CuentaSaldo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.cliente
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CuentaSaldo }
     * 
     */
    public CuentaSaldo createCuentaSaldo() {
        return new CuentaSaldo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CuentaSaldo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Cliente", name = "CuentaSaldo")
    public JAXBElement<CuentaSaldo> createCuentaSaldo(CuentaSaldo value) {
        return new JAXBElement<CuentaSaldo>(_CuentaSaldo_QNAME, CuentaSaldo.class, null, value);
    }

}
