//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.10 at 11:23:36 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Cliente", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.cliente;
